services:
  nest_api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - ${API_PORT}:${API_PORT}
    environment:
      - TYPEORM_HOST=db_postgres
      - TYPEORM_PORT=${TYPEORM_PORT}
      - TYPEORM_USERNAME=${TYPEORM_USERNAME}
      - TYPEORM_PASSWORD=${TYPEORM_PASSWORD}
      - TYPEORM_DATABASE=${TYPEORM_DATABASE}
      - API_PORT=${API_PORT}
    networks:
      - docker-network
    depends_on:
      - db_postgres
  db_postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: ${TYPEORM_USERNAME}
      POSTGRES_PASSWORD: ${TYPEORM_PASSWORD}
      POSTGRES_DB: ${TYPEORM_DATABASE}
    networks:
      - docker-network
    ports:
      - ${TYPEORM_PORT}:${TYPEORM_PORT}
    volumes:
      - api_db_data:/var/lib/postgresql/data
networks:
  docker-network:
volumes:
  api_db_data:
